# Checks that all checkboxes in a PR are checked
name: Checkboxes

on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
      - edited
  issue_comment:
    types:
      - created
      - edited

concurrency:
  group: ${{ github.event.pull_request.number || github.event.issue.number }}-pr-checkboxes
  cancel-in-progress: true

defaults:
  run:
    shell: bash

permissions:
  contents: "read"
  pull-requests: "read"

jobs:
  pr-checkboxes:
    if: github.event_name == 'pull_request_target' || github.event.issue.pull_request
    name: Check PR checkboxes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          pip install PyGithub

      - name: Check PR checkboxes
        run: |
          pixi run ./github/scripts/checkboxes.py \
            --github-token ${{ secrets.GITHUB_TOKEN }} \
            --github-repository ${{ github.repository }} \
            --pr-number ${{ github.event.pull_request.number || github.event.issue.number }}

